import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "./(main)/components/navbar/NavBar";

const montserrat = Montserrat();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const revalidate = 60;
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <NavBar />
        <main className="px-2 md:px-4 lg:px-24 xl:px-36 2xl:px-72 pt-20">
          {children}
        </main>
      </body>
    </html>
  );
}
